language: java
jdk: oraclejdk8
services:
  - docker
script:
  - "./gradlew check"
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
  - SPRING_PROFILES_ACTIVE=default,integration-tests
  - secure: gRGkkNjdpbiRiLIiYUr4cXU1HhswQiH4Gws2pMobpmwogGOjw/029tTRd1a3ZermcZ6sKXw4wxoqMmkhcKm2LuUZSRbTysyHLjHQACLbZAnNu9xfRCJb6zDsdVISJ96J2LwDleE4Tr5ufXQZ3mNDzI1dQLT3hmHoNZA8054VdP4Uo75SMWOm2qsMX+ngShaGyEWoZaghR/BRbJQ0o9r+zL6wBrKucBZWDXo+ea1LrP6vaD87DZ6ehmrLUlhmnI2JxzuSU2Up+dq7mLQ0AGDR2XheUDvzws1FlfdJA+rZycUY6Pz1nsmDRn47yffRVrL9SZ4uV7iYldALVfjLOnMjd0RjEm0JzfNjPPz3f4WF9jofJz4/d44QDU1tZR0mre2UpHtSnBxdUyNkoTmP0h64GemHkRvk3f5Lz6g/vKUAJ98/NSCP8SnsGvEe3FYZugVxSo0vD0uqs5JDyboKukY+6MC0haDUIszrH7e8UgeI21zbGechOn0BB3xIH27ZvvPZEhJ92TwC+fhlUgGv8iMNn6NnTXdQyv5ItAAuwsHcYMXBmZgvywJ1Z4KdvjoMa04CcAbh3kV5O+dSF8J4txvIevLACjyKFe5jQpG2Zls/o8VK0YXJLRwwqP9s+RyPy4rJpwcnKBsUYpw9GHDVqpfp+4K6uDNHj3xDORR0Kk9bl2g=
  - secure: jbSuEZ67wAs9oMcXx3QlS2fDUvpEo0Q+DkHfT0Pf7KnDmIDeayaheSZWyGuu+GO2kTAX9J/Io4rY/WZJBHE1HaEkEawAfZzm/b2LaI4Kmmq9iFHWh/hDs+6bWqNXOujC+VRtE4O5LnhBC32jwkqWQMXNxP1DjjPegl4V+gP+8L1SWypWEREQ16I1BrvnzR0Jpf+a/rlGF+5Egui+dvZJd7dywWeYUmo+DpCxkyoA9ZsYNpd9VDBSxampqrmdeImllo1Bw+1Jkv6Wn6IppyYVpXQHifPJc6xLfRHELAefNzR7MYC00P0urihC96c1yuLpxovVJFcZHU25XQMJIIBDPZT2AVDsdyUSOoYuqqIrpkknUR6gPnxkD+aitJaHVtef8eG7VDVJYHYyvFrBNhbgeJ9QMv0wAVjf71rD9gOGZ9PBlCAwK/AgjeqzwJ0CGYG15/IgZaed8L7aJVpAjbS9sWxVtWD0nIEZa8wtOGCOKqNgqG3ZizdvMe6nE3YJQnyU0JsxmAsQaSnjby+gvBPr/ZTgV+pnKA/gFVlxR8p/SpFpuRZDxDwJ5KovH6a/LK7hDXYS8YGUq8VSImtCztaqB+G/3bJoCkA5zDlvnslS3JsYvEeuEXFPloLHgDN3T1O5WO+Kj2wKhv3rYQ8iB0E+tkOXNAX95bLnsJNvzEggatU=
branches:
  only:
    - master
notifications:
  slack:
    secure: zeLxHE+z8RXsge7imwHbv4HuqpsMWlnvDXovlZH3iQW//6TrsgYT4arEp/NDV6jTYtMgLWmm4ou2nLu+AaYLmXIkp4Pt8z0xKnx8NPT8UsZn7f6gqK7Abah4YnrB4uHwnVzzVNlb0jmjWClVCNxR73GI+324pnxOjOSP4In8iCwX+fm9yKAhlaE1VMTVsjE2oTl+ECECmG4fWmDthg1gb6edLquUX04fhc0gDBmQ4c0mxoBSfhAI3eV22IehOiRMBwElPAcfZ0bWDK19AniGfYeyWYX+a1v4Mxy880oxsFIeCqJBQTw7j0DslF0VoZeJw2GTsecC2FTB9JiYX24wy/hCsAtwIZB/JX4znx5CsyDbKpvL1bcfKLg0MuBbZAkqFLS6K0pppgMd1McH2Og+ZTZyIogbWtW4Hvvgn9fNoU3RosxM3xwRcI560DjGdEKjuZikxC5mcuMuiNKR7rFNL8wA5beHc+yNBoF2VHuuJOG4zTgG0FOfdn4Chd9b+NN23Jhdny0WwCOfFneVfOkgkAvlvtN73YImlKHYBb3rE9/+lqAuwxmpYumKrkOFt95WW4vEBW2mUi4txYNK8uuTVA7CM+/h8mkAcgX9f0uES+fRA5/vegPnZuRVcnGhgLEQZ4EgYts0jJtYI+RzPuSMiMDA2R/Prgq/SvPhTmBwWxE=
    on_failure: always
    on_success: never
after_script:
  - if [ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" == "false" ];
    then echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin;
    docker build -t fwmtstaffsvc --build-arg jar=build/libs/fwmt-staff-service-1.0.0.jar .;
    docker tag fwmtstaffsvc sdcplatform/fwmtstaffsvc:$TRAVIS_BUILD_NUMBER;
    docker push sdcplatform/fwmtstaffsvc;
    fi
